### ISSUE TITLE
Star War Site ☄️

### ISSUE THREAD

**Issue by Abbhiishek** [its-puneet/Geeky-Coders#13]
**Is your feature request related to a problem? Please describe.**

## A dynamic website for Star War Characters

**Describe the solution you'd like**

**Comment by spiderxp3** [comment]
I want to work on this.

**Comment by its-puneet** [comment]
Go ahead but make sure to upload your whole project in a folder.

**Comment by Abbhiishek** [comment]
Hey @spiderxp3  sure , if maintainers permits
