### ISSUE TITLE
POSTFIX CALCULATOR USING PYTHON

### ISSUE THREAD

**Issue by Nirvik07** [its-puneet/Geeky-Coders#47]
**Is your feature request related to a problem? Please describe.**
A calculator which converts infix expression to postfix expression

**Describe the solution you'd like**
I will create a Tkinter app using python for this calculator 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Nirvik07** [comment]
@its-puneet assign me this

**Comment by Nirvik07** [comment]
@its-puneet please assign it to me.

**Comment by its-puneet** [comment]
Go ahead

**Comment by Nirvik07** [comment]
@its-puneet could put the Hacktoberfest label?
